drop table IF EXISTS comments cascade;
drop table IF EXISTS bookings cascade;
drop table IF EXISTS items cascade;
drop table IF EXISTS requests cascade;
drop table IF EXISTS users cascade;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    email varchar(500) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(1000) NOT NULL,
    requestor_id BIGINT REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available boolean,
    owner_id BIGINT references users (id),
    request_id BIGINT references requests(id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    item_id BIGINT references items (id),
    booker_id BIGINT references users (id),
    status varchar (30)
);

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(100) NOT NULL,
    item_id BIGINT references items (id),
    author_id BIGINT references users (id),
    created timestamp without time zone
);